# Generated by Django 4.2.7 on 2024-01-16 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='circus',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('FullName', models.CharField(max_length=100, verbose_name='name')),
                ('IsAlive', models.BooleanField(default=False, verbose_name='is alive')),
                ('HowManyDalghakIsTrained', models.IntegerField(verbose_name='HowManyDalghakIsTrained')),
            ],
            options={
                'verbose_name_plural': 'dalghak haha',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('GenName', models.CharField(max_length=100, verbose_name='gener')),
            ],
        ),
        migrations.CreateModel(
            name='dalghak',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('Name', models.CharField(max_length=100, verbose_name='name')),
                ('DalghakSalary', models.SmallIntegerField(verbose_name='Dalghak salary')),
                ('WhenBecomeDalghak', models.DateField(max_length=100, verbose_name='id')),
                ('IsAlive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aaaa.circus')),
            ],
        ),
    ]
